### PR TITLE
Untyped names migration

### PR DESCRIPTION
**Pull request by kspurgin**
Changes/updates to date. The commit messages say what changed. 

(I guess the git config on the server has got the user set to Nigel!)

### CODE REVIEW

**Comment by kspurgin** [comment]
@nigelgbanks - how should we proceed with this? I can just keep adding commits to this, or should we merge it or what. I confess I have not dealt with a public fork of code before.

**Comment by nigelgbanks** [comment]
I think we can just maintain our changes on the existing branch. No need to merge into master, it might be easier just to keep it in sync with the upstream.

**Comment by nigelgbanks** [comment]
I've done a rebase so the commits are associated with your account and changed the default user on the server to you.

**Comment by kspurgin** [comment]
@nigelgbanks -- so the idea is: we will keep master in sync with upstream, my changes in this branch (I'll look up how to rename a branch), and that'll make it easy to see what our customizations are, right?

**Comment by kspurgin** [comment]
I switched these changes to a the `migration-changes` branch.

**Comment by nigelgbanks** [comment]
Sounds good to me

**Pull request closed without merging**
